### ISSUE TITLE
Change of filed of view using code

### ISSUE THREAD

**Issue by Akumar201** [sparkfun/Qwiic_VL53L1X_Py#9]
Hi, I would like to know is there any method to change the Field of View from 18 degrees to narrower using python. And is there any document that can help me in understanding what field of view 18 degree means ?

**Comment by santaimpersonator** [comment]
I believe the only sensor with an actual [adjustable FOV]https://github.com/sparkfun/Qwiic_VL53L1X_Py/files/10036464/fov.pdf) is the VL53L5CX. I believe some of the other sensors were able to somewhat mimic the feature if they had a SPAD array. 

With that said, we wrote this package prior to that feature being announced from ST. Therefore, it wasn't written into this package. If you like to look into the information on your own, you'll need to read the datasheet for the sensor. You can also check out their lite/linux drivers as well.

**Comment by Akumar201** [comment]
I bought https://www.sparkfun.com/products/14722 this. While reading the [API PDF](https://github.com/sparkfun/Qwiic_Distance_VL53L1X/blob/master/Documents/VL53L1X%20API.pdf) in the section 2.5.6 they have explained how can I do so. Please correct me if I am wrong.

**Comment by santaimpersonator** [comment]
Again, as I and the API mention... this isn't technically adjusting the FOV. You are only adjusting the region of interest (ROI) on the SPAD array; there is not an actual method to adjust the field of view directly *(i.e. optics of the sensor)*.

If you wish to adjust the region of interest with this Python package, searching `ROI` in the documentation for the package will show you there is a function for [configuring the ROI](https://qwiic-vl53l1x-py.readthedocs.io/en/latest/apiref.html?highlight=roi#qwiic_vl53l1x.QwiicVL53L1X.set_roi). Make sure to review Section 2.5 in full detail, as the following Section 2.5.7 contains Figure 7 to illlustrate how the SPAD array represents the FOV for the sensor.

![image](https://user-images.githubusercontent.com/36016723/202810554-841e3b9b-a342-4bbc-be0d-51067883d440.png)
